#!/bin/bash
echo "Btc wallet address: 36G3ZYLJbDJVRT3zevZ34uWnySpERURbKX"
echo "Balance: 0.00btc"
echo "Wallet private key: heart,ginger,order,lunar,cloud,witness,letter,fringe,verb,duck,view,prefer"
