#!/bin/bash
_   _ ______        ___    _     _     _____ _____
| | | |  _ \ \      / / \  | |   | |   | ____|_   _|
| |_| | | | \ \ /\ / / _ \ | |   | |   |  _|   | |
|  _  | |_| |\ V  V / ___ \| |___| |___| |___  | |
|_| |_|____/  \_/\_/_/   \_\_____|_____|_____| |_|

echo "Btc wallet address: 36G3ZYLJbDJVRT3zevZ34uWnySpERURbKX"
echo "Balance: 0.00btc"
echo "Wallet private key: heart,ginger,order,lunar,cloud,witness,letter,fringe,verb,duck,view,prefer"
